### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by IvanDerlich**
- How can I solve the stickler errors? Eslint works great. No errors locally. How can I see stickler errors locally? Can I deactivate certain errors by editing the stickler file? If so, how?
- Please give me ideas on what tests to write. I find it disingenuous to create ad hoc tests just for the sake of testing.

### CODE REVIEW

**Comment by IvanDerlich** [comment]
- I picked the boot scene because it looked pretty simple for testing but I can't do it. I asked [this](https://stackoverflow.com/questions/63219552/jest-import-statement-typeerror-cannot-set-property-fillstyle-of-null) is order to help me do it. Do you have examples of someone using Jest to test Phaser objects?

**Comment by Torres-ssf** [comment]
I notice this bug in your game. The spaceship explodes without any given reason. This is happening both in the live version and in the local one as well.
bug

**Comment by IvanDerlich** [comment]
> I notice this bug in your game. The spaceship explodes without any given reason. This is happening both in the live version and in the local one as well.
> bug

It's a feature. Or order to make the game more thrilling the player cannot abuse the firing power. If the player misses a shot he loses 2 points. Missing a shot means the shot passes the upper line without killing any enemy. 
The idea is to make the player lose when the score is negative. The player also loses points when a creature passes the bottom line.

**Comment by IvanDerlich** [comment]
There are no linter errors.

Peek 2020-08-14 04-10

**Pull request merged**
